spring.application.name=order-service

server.port=8083
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:order_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672

management.tracing.sampling.probability=1.0