name: CD - Local Deploy

on:
  push:
    branches: [ "feature/cd-test" ]
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: docker compose down
        working-directory: ${{ github.workspace }}

      - name: Cleanup old Docker images
        run: docker image prune -f

      - name: Build and start all services
        run: docker compose up -d --build
        working-directory: ${{ github.workspace }}

      - name: Wait for services to be healthy
        run: Start-Sleep -Seconds 40
        shell: pwsh

      - name: Post-deploy health check - user-service
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:8081/actuator/health" -UseBasicParsing
          if ($response.StatusCode -ne 200) { exit 1 }
        shell: pwsh

      - name: Post-deploy health check - product-service
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:8082/actuator/health" -UseBasicParsing
          if ($response.StatusCode -ne 200) { exit 1 }
        shell: pwsh

      - name: Post-deploy health check - order-service
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:8083/actuator/health" -UseBasicParsing
          if ($response.StatusCode -ne 200) { exit 1 }
        shell: pwsh

      - name: Post-deploy health check - notification-service
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:8084/actuator/health" -UseBasicParsing
          if ($response.StatusCode -ne 200) { exit 1 }
        shell: pwsh

      - name: Post-deploy health check - api-gateway
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:8080/actuator/health" -UseBasicParsing
          if ($response.StatusCode -ne 200) { exit 1 }
        shell: pwsh

      - name: Deploy successful
        run: echo "All services are healthy. Deploy completed successfully."